import { readFileSync } from 'node:fs';
import { loadConfig, initialState, advance, replay } from './core/src/index.ts';
const loaded = loadConfig(JSON.parse(readFileSync('tuning/default.json', 'utf8')));
console.log('maxAdvanceMs =', loaded.maxAdvanceMs);
const s0 = initialState(loaded, 0);
console.log('t0', JSON.stringify(s0.stats));
const DAY = 86400000;
const oneShot = advance(loaded, s0, 3 * DAY);
console.log('3d one-shot ', JSON.stringify(oneShot.stats), JSON.stringify(oneShot.rem));
let step = s0;
for (let i = 0; i < 72; i++) step = advance(loaded, step, 3600000);
console.log('3d 72 steps ', JSON.stringify(step.stats), JSON.stringify(step.rem));
console.log('MATCH:', JSON.stringify(oneShot) === JSON.stringify(step));
const r = replay(loaded, s0, [{atMs: 3600000, kind:'feed'}, {atMs: 1800000, kind:'play'}], 2*DAY);
console.log('replay 2d', JSON.stringify(r.stats));
